### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by Todagit** [Todagit/chat-space#12]
# IPアドレス
18.180.9.222

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

### [修正箇所]
**①写真の表示位置を調整しましょう！**
<img width="669" alt="スクリーンショット 2020-06-16 12 07 02" src="https://user-images.githubusercontent.com/49669977/84729225-278e9180-afce-11ea-8646-4f8171b7780e.png">


修正が完了次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by Todagit** [comment]
ご指摘いただいた箇所なのですが、Scssのファイルを確認したところ色の指定はカリキュラム通り#eeeeeeになっていると思いますが、再度ご確認いただけないでしょうか？
GyazoのURLもご参照ください。
https://gyazo.com/02a4534237b6d40599c438ef66c3735e

**Comment by mutorisa** [comment]
ご提出ありがとうございます！
再度確認させて頂きましたが、区切りの色はカリキュラム通りになっておりました。
失礼いたしました。
修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！！

※今後実装に関するご質問がございましたら、メンターに相談いただきますようお願いします。
